# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPa-GFEt1ehMZxTmc8kjkne0W36ySFJx
"""

n=5
for i in range(1,n+1):
  print(i,end=" ")
for j in range(n-1,0,-1):
  print(j,end=" ")

def fun(n):
  if n==1:
    return 0
  elif n%2 == 0:
    return 1+ fun(n//2)
  else:
    return 1+min(fun(n-1),fun(n+1))
n=24
print(fun(n))

def fun(l,i=0):
  if i==len(l):
    return 0
  return l[i]+fun(l,i+1)
l=[1,4,3,2,5]
print(fun(l))

def fun(n,i=2):
  if i==len(l):
    return 0
  if prime(l(i)):
    return 1+fun(l,i+1)
  else:
    return fun(l,i+1)
l=[11,4,3,6,5]

n=12
result=1
for i in range(1,n+1):
  result *= i
print(result)

def fib(n):
  if n==0 or n==1:
    return n
  return fib(n-1)+fib(n-2)
n=5
print(fib(n))